### ISSUE TITLE
problem on 1.10.2 and new ic2

### ISSUE THREAD

**Issue by changemenemo** [Darkhax-Minecraft/Tesla#48]
hi, 
I know that you've gone to 1.11.2 and 1.12. but is it somewhat possible to have a fix for this bug from ic2?
```
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_141]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
... 5 more
Caused by: java.lang.ClassCastException: ic2.core.block.wiring.TileEntityElectricBatBox cannot be cast to ic2.api.energy.tile.IEnergySource
at org.cyclops.energysynergy.modcompat.ic2.capability.tesla.Ic2TeslaIntegration$3.createProvider(Ic2TeslaIntegration.java:72) ~[Ic2TeslaIntegration$3.class:?]
at org.cyclops.cyclopscore.modcompat.capabilities.SimpleCapabilityConstructor.createProvider(SimpleCapabilityConstructor.java:18) ~[SimpleCapabilityConstructor.class:?]
at org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry.createProvider(CapabilityConstructorRegistry.java:149) ~[CapabilityConstructorRegistry.class:?]
at org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry.addLoadedCapabilityProvider(CapabilityConstructorRegistry.java:186) ~[CapabilityConstructorRegistry.class:?]
at org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry.onLoad(CapabilityConstructorRegistry.java:180) ~[CapabilityConstructorRegistry.class:?]
at org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry.onLoad(CapabilityConstructorRegistry.java:155) ~[CapabilityConstructorRegistry.class:?]
at org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry.onTileLoad(CapabilityConstructorRegistry.java:199) ~[CapabilityConstructorRegistry.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1_CapabilityConstructorRegistry_onTileLoad_TileEntity.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:565) ~[ForgeEventFactory.class:?]
at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:545) ~[ForgeEventFactory.class:?]
at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:489) ~[aqk.class:?]
at ic2.core.block.TileEntityBlock.<init>(TileEntityBlock.java:83) ~[TileEntityBlock.class:?]
at ic2.core.block.TileEntityInventory.<init>(TileEntityInventory.java:32) ~[TileEntityInventory.class:?]
at ic2.core.block.wiring.TileEntityElectricBlock.<init>(TileEntityElectricBlock.java:50) ~[TileEntityElectricBlock.class:?]
at ic2.core.block.wiring.TileEntityElectricBatBox.<init>(TileEntityElectricBatBox.java:12) ~[TileEntityElectricBatBox.class:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_141]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_141]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_141]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_141]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_141]
at ic2.core.block.TileEntityBlock.instantiate(TileEntityBlock.java:77) ~[TileEntityBlock.class:?]
at ic2.core.item.block.ItemBlockTileEntity.placeBlockAt(ItemBlockTileEntity.java:89) ~[ItemBlockTileEntity.class:?]
at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54) ~[acl.class:?]
at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:780) ~[ForgeHooks.class:?]
at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:145) ~[adz.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:493) ~[lv.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_141]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_141]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
... 5 more
```

**Comment by changemenemo** [comment]
the version of industrial craft is 2.2.6.252 and 253

**Comment by RogueLogix** [comment]
This is an IC2 error and it not related to Tesla code in any way.
